#+STARTUP: showeverything
#+TITLE: passion paradist
#+AUTHOR: Danny McClanahan
#+EMAIL: (format "%s@%s.com" "danieldmcclanahan" "gmail")

Press the =?= key to see movement and usage commands.

* about this site

This site was generated by [[about me][me]] from static files using [[https://gnu.org/software/emacs][emacs]] and [[http://orgmode.org][org-mode]]. The [[https://github.com/cosmicexplorer/org-site-creator][generator]] is by no means production quality code, but it works pretty reliably and doesn't harvest your personal information (probably). The site supports org-mode's linking features (here's [[file:test.c]] from this repo), as well as org-babel; here's some inline code:
#+BEGIN_SRC javascript
console.log("hello world!");

var a = 3; // set a to 3

var f = function(){
  this.x = a;
}

var g = new f;
#+END_SRC

The highlighting of code blocks runs off [[https://highlightjs.org][highlight.js]]. It's interesting to note that all these interconnected pages are actually a single page! Such is the magic of [[https://github.com/cosmicexplorer/org-info-js][org-info.js]] (which I've sprinkled a little extra pizazz on).

Since the site generation is totally static (the generated site doesn't rely on external resources), I'd like to try making it a more generic sort of local documentation generator. But that'll come after I write code that needs documentation.

** about me

I'm Danny McClanahan. I [[https://github.com/cosmicexplorer][write code]] and [[posts][occasionally scribble on the internet]]. I'm an undergraduate at Vanderbilt University and most of my friends think I'm cool; feel free to disagree.

* posts

I often find that writing about things is harder for me to do than to actually do them, so this is an attempt to combat that. To search through posts, you can either [[https://github.com/cosmicexplorer/cosmicexplorer.github.io][clone this repo]] or press the =o= key to run occur mode.

** initial reaction
